                             -- QUAN LI BAN HANG --
CREATE DATABASE QLBH
USE QLBH


CREATE TABLE KHACHHANG
(
MAKH CHAR(4) PRIMARY KEY,
HOTEN VARCHAR(40),
DCHI VARCHAR(50),
SODT VARCHAR(20),
NGSINH SMALLDATETIME,
NGDK SMALLDATETIME,
DOANHSO MONEY,
)
CREATE TABLE NHANVIEN
(
MANV CHAR(4) PRIMARY KEY,
HOTEN VARCHAR(40),
SODT VARCHAR(20),
NGVL SMALLDATETIME,
)
CREATE TABLE SANPHAM
(
MASP CHAR(4) PRIMARY KEY,
TENSP VARCHAR(40),
DVT VARCHAR(20),
NUOCSX VARCHAR(40),
GIA MONEY,
)
CREATE TABLE HOADON
(
SOHD INT PRIMARY KEY,
NGMH SMALLDATETIME  ,
MAKH CHAR(4) REFERENCES KHACHHANG(MAKH),
MANV CHAR(4) REFERENCES NHANVIEN(MANV),
TRIGIA MONEY,
)
CREATE TABLE CTHD
(
SOHD INT REFERENCES HOADON(SOHD),
MASP CHAR(4) REFERENCES SANPHAM(MASP),
SL INT,
PRIMARY KEY(SOHD, MASP),
)

ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(20)

ALTER TABLE SANPHAM
DROP COLUMN GHICHU

ALTER TABLE KHACHHANG
ADD CONSTRAINT CHECK_LOAIKH CHECK (LOAIKH='Vang lai' OR LOAIKH='Thuong xuyen' OR LOAIKH='Vip');
ALTER TABLE SANPHAM
ADD CONSTRAINT CHECK_DVT CHECK(DVT='CAY'OR DVT='CAI'OR DVT='HOP'OR DVT='QUYEN'OR DVT='CHUC');

ALTER TABLE SANPHAM
ADD CONSTRAINT CHECK_GIA CHECK(GIA>=500);

ALTER TABLE HOADON
ADD CONSTRAINT CHECK_SP CHECK(TRIGIA>0);

ALTER TABLE KHACHHANG
ADD CONSTRAINT CHECK_NGAY CHECK(NGDK<NGSINH)

                     --QUAN LI GIAO VU-- 

CREATE DATABASE QLGV
USE QLGV

CREATE TABLE KHOA 
(
MAKHOA VARCHAR(4) PRIMARY KEY,
TENKHOA VARCHAR(40),
NGTLAP SMALLDATETIME,
TRGKHOA CHAR(4),
)
CREATE TABLE MONHOC 
(
MAMH VARCHAR(10) PRIMARY KEY,
TENMH VARCHAR(40),
TCLT TINYINT,
TCTH TINYINT,
MAKHOA VARCHAR(4),
)
CREATE TABLE DIEUKIEN
(
MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
MAMH_TRUOC VARCHAR(10) REFERENCES MONHOC(MAMH),
PRIMARY KEY(MAMH, MAMH_TRUOC)
)
CREATE TABLE GIAOVIEN
(
MAGV CHAR(4) PRIMARY KEY,
HOTEN VARCHAR(40) ,
HOCVI VARCHAR(10) ,
HOCHAM VARCHAR(10) ,
GIOITINH VARCHAR(3) ,
NGSINH SMALLDATETIME,
NGVL SMALLDATETIME,
HESO NUMERIC(4,2),
MUCLUONG MONEY,
MAKHOA VARCHAR(4) REFERENCES KHOA(MAKHOA),
)
CREATE TABLE LOP 
(
MALOP CHAR(3) PRIMARY KEY,
TENLOP VARCHAR(40),
TRGLOP CHAR(5),
SISO TINYINT,
MAGVCN CHAR(4) REFERENCES GIAOVIEN(MAGV),
)
CREATE TABLE HOCVIEN
(
MAHV CHAR(5) PRIMARY KEY,
HO VARCHAR(40),
TEN VARCHAR(10),
NGSINH SMALLDATETIME,
GIOITINH VARCHAR(3),
NOISINH VARCHAR(40),
MALOP CHAR(3) REFERENCES LOP(MALOP),
)
CREATE TABLE GIANGDAY
(
MALOP CHAR(3) REFERENCES LOP(MALOP),
MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
MAGV CHAR(4) REFERENCES GIAOVIEN(MAGV),
HOCKY TINYINT,
NAM SMALLINT,
TUNGAY SMALLDATETIME,
DENNGAY SMALLDATETIME,
PRIMARY KEY(MALOP, MAMH)
)
CREATE TABLE KETQUATHI
(
MAHV CHAR(5) REFERENCES HOCVIEN(MAHV),
MAMH VARCHAR(10) REFERENCES MONHOC(MAMH),
LANTHI TINYINT,
NGTHI SMALLDATETIME,
DIEM NUMERIC(4,2),
KQUA VARCHAR(10),
PRIMARY KEY(MAHV, MAMH, LANTHI)
)

ALTER TABLE HOCVIEN 
ADD CONSTRAINT CK_GIOITINH CHECK(GIOITINH IN ('Nam', 'Nu'))

-- 4.	?i?m s? c?a m?t l?n thi có giá tr? t? 0 ??n 10 và c?n l?u ??n 2 s? l? (VD: 6.22).
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM CHECK(
	DIEM BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(DIEM AS VARCHAR), CHARINDEX('.', DIEM) + 1, 1000)) >= 2
)

-- 5.	K?t qu? thi là “Dat” n?u ?i?m t? 5 ??n 10  và “Khong dat” n?u ?i?m nh? h?n 5.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KQUA CHECK(KQUA = IIF(DIEM BETWEEN 5 AND 10, 'Dat', 'Khong dat'))

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_SOLANTHI CHECK(LANTHI <= 3)

ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY CHECK(HOCKY BETWEEN 1 AND 3)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HOCVI CHECK(HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

-